apiVersion: v1
kind: Service
metadata:
  name: ollama-qwen-30b-gpu
spec:
  type: NodePort
  selector:
    app: ollama-qwen-30b-gpu
  ports:
    - protocol: TCP
      port: 8000         # container port
      targetPort: 8000   # container port
      nodePort: 29000    # expose on node
